#!/usr/bin/env bash
# Vendors libusb and librtlsdr into android/src/main/cpp/vendor/.
#
# The sources are already committed to the repository — this script exists
# to re-vendor/update the libs in the future (a new tag, or a setup on
# another machine if the vendor/ directories were removed), reproducing
# exactly the process used to generate the current state.
#
# Fixed tags (not branches) for reproducibility. License: libusb is
# LGPL-2.1, librtlsdr is GPLv2 — see docs/native_build.md.
set -euo pipefail

LIBUSB_TAG="v1.0.30"
LIBRTLSDR_TAG="v2.1.0"
KISSFFT_TAG="v131"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CPP_DIR="$ROOT_DIR/android/src/main/cpp"
VENDOR_DIR="$CPP_DIR/vendor"
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

echo "==> Downloading libusb $LIBUSB_TAG"
curl -sL "https://codeload.github.com/libusb/libusb/tar.gz/refs/tags/${LIBUSB_TAG}" -o "$WORK_DIR/libusb.tar.gz"
mkdir -p "$WORK_DIR/libusb-src"
tar xzf "$WORK_DIR/libusb.tar.gz" -C "$WORK_DIR/libusb-src" --strip-components=1

echo "==> Downloading librtlsdr $LIBRTLSDR_TAG"
curl -sL "https://codeload.github.com/librtlsdr/librtlsdr/tar.gz/refs/tags/${LIBRTLSDR_TAG}" -o "$WORK_DIR/librtlsdr.tar.gz"
mkdir -p "$WORK_DIR/librtlsdr-src"
tar xzf "$WORK_DIR/librtlsdr.tar.gz" -C "$WORK_DIR/librtlsdr-src" --strip-components=1

echo "==> Vendoring libusb (files listed in libusb's own android/jni/libusb.mk)"
LIBUSB_DST="$VENDOR_DIR/libusb"
rm -rf "$LIBUSB_DST"
mkdir -p "$LIBUSB_DST/libusb/os" "$LIBUSB_DST/android_config"
SRC="$WORK_DIR/libusb-src"
for f in core.c descriptor.c hotplug.c io.c sync.c strerror.c; do
  cp "$SRC/libusb/$f" "$LIBUSB_DST/libusb/$f"
done
for f in linux_usbfs.c events_posix.c threads_posix.c linux_netlink.c linux_usbfs.h events_posix.h threads_posix.h; do
  cp "$SRC/libusb/os/$f" "$LIBUSB_DST/libusb/os/$f"
done
cp "$SRC/libusb/libusb.h" "$SRC/libusb/libusbi.h" "$SRC/libusb/version.h" "$SRC/libusb/version_nano.h" "$LIBUSB_DST/libusb/"
cp "$SRC/android/config.h" "$LIBUSB_DST/android_config/config.h"
cp "$SRC/COPYING" "$LIBUSB_DST/COPYING.LGPL-2.1"

echo "==> Vendoring librtlsdr (library sources only, without the rtl_*.c utilities)"
RTLSDR_DST="$VENDOR_DIR/librtlsdr"
rm -rf "$RTLSDR_DST"
mkdir -p "$RTLSDR_DST/src" "$RTLSDR_DST/include"
SRC="$WORK_DIR/librtlsdr-src"
for f in librtlsdr.c tuner_e4k.c tuner_fc0012.c tuner_fc0013.c tuner_fc2580.c tuner_r82xx.c; do
  cp "$SRC/src/$f" "$RTLSDR_DST/src/$f"
done
for f in rtl-sdr.h rtl-sdr_export.h rtlsdr_i2c.h rtlsdr_rpc.h tuner_e4k.h tuner_fc0012.h tuner_fc0013.h tuner_fc2580.h tuner_r82xx.h reg_field.h; do
  cp "$SRC/include/$f" "$RTLSDR_DST/include/$f"
done
cp "$SRC/COPYING" "$RTLSDR_DST/COPYING.GPLv2"

# rtl_app_ver.h is normally generated by the project's CMake from the .in
# file; since we don't use their build system, we generate a fixed one here.
cat > "$RTLSDR_DST/src/rtl_app_ver.h" <<EOF
#ifndef __RTL_APP_VER_H
#define __RTL_APP_VER_H

#define APP_VER_MAJOR	2
#define APP_VER_MINOR	1
#define APP_VER_ID	"github.com/librtlsdr (vendored, Android)"

#define VER_TO_STRING(x)	#x
#define VAL_VER_TO_STR(x)	VER_TO_STRING(x)

#endif
EOF

echo "==> Applying rtlsdr_open_fd patch (Android fd handoff, no libusb enumeration)"
patch "$RTLSDR_DST/src/librtlsdr.c" < "$VENDOR_DIR/librtlsdr_open_fd.patch"

# rtlsdr_open_fd.h declares the new function (not a modification of an
# existing file, so it doesn't show up in the .patch above) — generated
# directly here.
cat > "$RTLSDR_DST/include/rtlsdr_open_fd.h" <<'HEADER_EOF'
/*
 * Android-specific extension to librtlsdr: open a device from a
 * libusb_device_handle obtained via libusb_wrap_sys_device() over a file
 * descriptor that Android's UsbManager/UsbDeviceConnection (Java) already
 * opened and granted permission for.
 *
 * This is a small addition on top of the upstream v2.1.0 API (not part of
 * the official librtlsdr headers) — see vendor/librtlsdr_open_fd.patch for
 * the corresponding change in src/librtlsdr.c. Kept in a separate header
 * (rather than editing rtl-sdr.h) so upstream's public header stays
 * untouched and this stays a self-contained, reviewable addition.
 */
#ifndef __RTLSDR_OPEN_FD_H
#define __RTLSDR_OPEN_FD_H

#include <libusb.h>
#include "rtl-sdr.h"

#ifdef __cplusplus
extern "C" {
#endif

RTLSDR_API int rtlsdr_open_fd(rtlsdr_dev_t **out_dev, libusb_context *ctx, libusb_device_handle *devh);

#ifdef __cplusplus
}
#endif

#endif
HEADER_EOF

echo "==> Downloading KissFFT $KISSFFT_TAG"
curl -sL "https://codeload.github.com/mborgerding/kissfft/tar.gz/refs/tags/${KISSFFT_TAG}" -o "$WORK_DIR/kissfft.tar.gz"
mkdir -p "$WORK_DIR/kissfft-src"
tar xzf "$WORK_DIR/kissfft.tar.gz" -C "$WORK_DIR/kissfft-src" --strip-components=1

echo "==> Vendoring KissFFT (only the complex-to-complex core, without kiss_fftr/extra backends)"
KISSFFT_DST="$VENDOR_DIR/kissfft"
rm -rf "$KISSFFT_DST"
mkdir -p "$KISSFFT_DST"
SRC="$WORK_DIR/kissfft-src"
cp "$SRC/kiss_fft.c" "$SRC/kiss_fft.h" "$SRC/_kiss_fft_guts.h" "$KISSFFT_DST/"
cp "$SRC/COPYING" "$KISSFFT_DST/COPYING.BSD-3-Clause"

echo "==> Done. Review 'git diff' in android/app/src/main/cpp/vendor/ before committing."
